name: portfolio
description: Here you can find the most important things about me! links to my projects, some geeky blog posts and my Contact information if you need them!

# flutter pub run build_runner build --delete-conflicting-outputs
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  xml: ^6.1.0
  http: ^1.2.2
  html: ^0.15.0
  intl: ^0.19.0
  bloc: ^8.1.0
  just_audio: ^0.9.29
  shamsi_date: ^1.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  country_icons: ^3.0.0
  flutter_quill: ^10.8.5
  enum_to_string: ^2.0.1
  json_annotation: ^4.7.0
  dynamic_cached_fonts: ^1.0.0
  animated_box_decoration: ^0.0.5

  font_awesome_flutter:

dependency_overrides:
  font_awesome_flutter:
    path: dependencies/font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  
flutter:
  generate: true
  uses-material-design: false

  assets:
    - assets/images/bg.jpeg
    - assets/images/callbg.jpg
    - assets/resume.json
    - assets/ring.mp3

    - assets/font/times/regular.ttf
    - assets/font/material_icons.otf
    - assets/font/pnazanin/regular.ttf
    - assets/font/pnazanin/bold.ttf

    - assets/font/fa/fa-brands-400.ttf
    - assets/font/fa/fa-regular-400.ttf
    - assets/font/fa/fa-solid-900.ttf

  # fonts:
  #   - family: times_new_roman
  #     fonts:
  #       - asset: assets/font/TimesNewRoman/times_new_roman.ttf
  #         style: normal
  #   - family: IRANSans
  #     fonts:
  #       - asset: assets/font/iransans/ttf/IRANSansWeb_FaNum_Medium.ttf
  #         style: normal
  #       - asset: assets/font/iransans/ttf/IRANSansWeb_FaNum_Bold.ttf
  #         weight: 700