name: portfolio
description: Here you can find the most important things about me! links to my projects, some geeky blog posts and my Contact information if you need them!

# flutter pub run build_runner build --delete-conflicting-outputs
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  xml: ^6.1.0
  http: ^1.2.2
  html: ^0.15.0
  intl: ^0.19.0
  bloc: ^9.0.0
  
  just_audio: ^0.9.29
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any

  shamsi_date: ^1.0.1
  equatable: ^2.0.3
  flutter_bloc: ^9.0.0
  url_launcher: ^6.1.6
  country_icons: ^3.0.0
  flutter_svg: ^2.0.17
  flutter_quill: ^10.8.5
  enum_to_string: ^2.0.1
  json_annotation: ^4.7.0
  dynamic_cached_fonts: ^1.0.0
  animated_box_decoration: ^0.0.5

  font_awesome_flutter:
    path: dependencies/font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/bg.jpeg
    - assets/images/callbg.jpg
    - assets/resume.json
    - assets/ring.mp3

    - assets/font/times/regular.ttf
    - assets/font/material_icons.otf
    - assets/font/pnazanin/regular.ttf
    - assets/font/pnazanin/bold.ttf

    - assets/font/fa/fa-brands-400.ttf
    - assets/font/fa/fa-regular-400.ttf
    - assets/font/fa/fa-solid-900.ttf

  fonts:
  - family: times
    fonts:
      - asset: assets/font/times/regular.ttf
        weight: 400

  - family: pnazanin
    fonts:
      - asset: assets/font/pnazanin/regular.ttf
        weight: 400
      - asset: assets/font/pnazanin/bold.ttf
        weight: 900

  - family: FontAwesomeBrands
    fonts:
      - asset: dependencies/font_awesome_flutter/lib/fonts/fa-brands-400.ttf
        weight: 400
  - family: FontAwesomeRegular
    fonts:
      - asset: dependencies/font_awesome_flutter/lib/fonts/fa-regular-400.ttf
        weight: 400
  - family: FontAwesomeSolid
    fonts:
      - asset: dependencies/font_awesome_flutter/lib/fonts/fa-solid-900.ttf
        weight: 900
